---
title: "The making of the lollipop chart"
author: "Sana Pashankar"
format: html
editor: visual
---

# Setup

-   Load packages:

```{r}
#| label: load-packages

library(tidyverse)
library(openintro)
```

-   Prep data:

```{r}
#| label: mean-area-decade

duke_forest <- duke_forest %>%
  mutate(
    decade_built = (year_built %/% 10) * 10,
    decade_built_cat = case_when(
      decade_built <= 1940 ~ "1940 or before",
      decade_built >= 1990 ~ "1990 or after",
      TRUE ~ as.character(decade_built)
    )
  )

mean_area_decade <- duke_forest |>
  group_by(decade_built_cat) |>
  summarise(mean_area = mean(area))

mean_area_decade
```

# Lollipop chart

Recreate the lollipop chart from the slides.

```{r}
ggplot(mean_area_decade, aes(y = decade_built_cat, x = mean_area)) + 
  geom_segment(aes(y = decade_built_cat, yend = decade_built_cat, x = 0, xend = mean_area)) + 
  geom_point(size = 3) + 
  labs(x = "Mean area (square feet)", 
       y = "Decade built", 
         title = "Mean area of houses in Duke Forest, by decade built")
```
